import { MediaKitData } from './types';

export const initialMediaKitData: MediaKitData = {
  creator: {
    name: 'Sophia Menezes',
    title: 'Autenticidade & Beleza Real',
    subtitle: 'Criadora de conteúdo digital unindo autocuidado, rotina fitness, beleza e estilo de vida consciente para milhares de mulheres.',
    quote: '"Amor-próprio em movimento"',
    bioParagraph1: 'Sophia Menezes constrói uma comunicação transparente, sofisticada e próxima com uma comunidade fiel de mulheres modernas.',
    bioParagraph2: 'Seu conteúdo celebra o equilíbrio: rotina matinal com disciplina, saúde dos fios e tratamentos capilares, treinos energéticos e escolhas conscientes que inspiram transformação genuína.',
    location: 'São Paulo, SP • Brasil',
    niche: 'Beleza • Rotina • Fitness • Lifestyle',
    profilePhoto: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=800&auto=format&fit=crop',
    heroPhoto: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=800&auto=format&fit=crop',
    aboutPhoto: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=800&auto=format&fit=crop',
    closingPhoto: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?q=80&w=800&auto=format&fit=crop',
    heroPhotoPosition: '50% 15%',
    aboutPhotoPosition: '50% 50%',
    closingPhotoPosition: '50% 50%',
    profilePhotoPosition: '50% 50%',
  },
  metrics: {
    monthlyReach: 3700000,
    monthlyReachLabel: '3.7M+',
    totalEngagement: 480000,
    totalEngagementLabel: '480K+',
    monthlyImpressions: 5900000,
    monthlyImpressionsLabel: '5.9M+',
  },
  instagram: {
    handle: '@sophiamenezes',
    profileUrl: 'https://instagram.com',
    followers: '285K',
    reach: '2.4M/mês',
    engagement: '5.8%',
    viewsPerReels: '145K+',
    femaleAudience: 87,
    maleAudience: 13,
    ageData: [
      { range: '18 - 24 anos', percent: 28 },
      { range: '25 - 34 anos', percent: 54 },
      { range: '35 - 44 anos', percent: 14 },
      { range: '45+ anos', percent: 4 },
    ],
    cityData: [
      { city: 'São Paulo', percent: 42 },
      { city: 'Rio de Janeiro', percent: 19 },
      { city: 'Belo Horizonte', percent: 12 },
      { city: 'Curitiba', percent: 9 },
      { city: 'Outras capitais', percent: 18 },
    ],
    bestReelViews: '1.2M',
  },
  tiktok: {
    handle: '@sophiamenezes',
    profileUrl: 'https://tiktok.com',
    followers: '420K',
    likes: '6.8M',
    avgViews: '85K',
    viralRecord: '2.9M views',
    femaleAudience: 82,
    maleAudience: 18,
    ageData: [
      { range: '18 - 24 anos', percent: 46 },
      { range: '25 - 34 anos', percent: 41 },
      { range: '35+ anos', percent: 13 },
    ],
    cityData: [
      { city: 'São Paulo', percent: 38 },
      { city: 'Rio de Janeiro', percent: 22 },
      { city: 'Brasília', percent: 14 },
      { city: 'Porto Alegre', percent: 11 },
      { city: 'Outras', percent: 15 },
    ],
  },
  segments: [
    {
      id: 'seg-1',
      tag: 'BELEZA',
      title: 'Cuidados Capilares',
      description: 'Rotina de cronograma capilar, testes reais de dermocosméticos, finalização e dicas que transformam a saúde dos fios.',
    },
    {
      id: 'seg-2',
      tag: 'DIA A DIA',
      title: 'Rotina Real',
      description: 'Vlogs e mini-vlogs que mostram o dia a dia sem filtros, organização pessoal, café matinal e produtividade leve.',
    },
    {
      id: 'seg-3',
      tag: 'FITNESS',
      title: 'Treinos & Saúde',
      description: 'Prática de musculação, hábitos saudáveis, alimentação equilibrada e suplementação como pilar de bem-estar.',
    },
    {
      id: 'seg-4',
      tag: 'BEM-ESTAR',
      title: 'Autoestima',
      description: 'Conversas francas sobre amor-próprio, saúde mental feminina e autoconfiança na rotina acelerada.',
    },
    {
      id: 'seg-5',
      tag: 'MODA & VIDA',
      title: 'Lifestyle & Moda Feminina',
      description: 'Composições elegantes, looks práticos de academia à rotina de trabalho e escolhas com estética limpa e refinada.',
    },
  ],
  brands: [
    {
      id: 'brand-1',
      name: 'Salon Line',
      status: 'active',
      category: 'Cachos & Capilar',
      campaignType: 'Embaixadora & Rotina Real',
      logoUrl: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=400&q=80',
      websiteUrl: 'https://www.salonline.com.br',
    },
    {
      id: 'brand-2',
      name: 'Principia Skincare',
      status: 'active',
      category: 'Dermocosméticos',
      campaignType: 'Rotina de Skincare Sem Filtro',
      logoUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=400&q=80',
      websiteUrl: 'https://www.principiaskincare.com.br',
    },
    {
      id: 'brand-3',
      name: "L'Oréal Paris",
      status: 'past',
      category: 'Beleza & Tratamento',
      campaignType: 'Lançamento Linha Glycolic Gloss',
      logoUrl: 'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?auto=format&fit=crop&w=400&q=80',
      websiteUrl: 'https://www.loreal-paris.com.br',
    },
    {
      id: 'brand-4',
      name: 'Growth Supplements',
      status: 'active',
      category: 'Fitness & Nutrição',
      campaignType: 'Cupom Oficial & Hábitos Saudáveis',
      logoUrl: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=400&q=80',
      websiteUrl: 'https://www.gsuplementos.com.br',
    },
    {
      id: 'brand-5',
      name: 'Wella Professionals',
      status: 'past',
      category: 'Tratamento Salon',
      campaignType: 'Transformação & Cronograma Capilar',
      logoUrl: 'https://images.unsplash.com/photo-1527799820374-dcf8d9d4a388?auto=format&fit=crop&w=400&q=80',
      websiteUrl: 'https://www.wella.com',
    },
    {
      id: 'brand-6',
      name: 'Schutz',
      status: 'past',
      category: 'Moda & Calçados',
      campaignType: 'Coleção Alto Verão & Styling',
      logoUrl: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=400&q=80',
      websiteUrl: 'https://www.schutz.com.br',
    },
    {
      id: 'brand-7',
      name: 'Simple Organic',
      status: 'active',
      category: 'Clean Beauty',
      campaignType: 'Autocuidado & Beleza Limpa',
      logoUrl: 'https://images.unsplash.com/photo-1608248597359-009581895a62?auto=format&fit=crop&w=400&q=80',
      websiteUrl: 'https://simpleorganic.com.br',
    },
    {
      id: 'brand-8',
      name: 'Dailus',
      status: 'past',
      category: 'Maquiagem & Cores',
      campaignType: 'Make do Dia a Dia & Unhas',
      logoUrl: 'https://images.unsplash.com/photo-1583241800698-e8ab01830a07?auto=format&fit=crop&w=400&q=80',
      websiteUrl: 'https://www.dailus.com.br',
    },
  ],
  contact: {
    email: 'Sophiaamenezes10@gmail.com',
    phone: '+55 (11) 99988-7766',
    whatsapp: '5511999887766',
    managerName: 'Assessoria Sophia Menezes',
    responseTime: 'Até 24h úteis',
  },
  partnershipFormats: [
    {
      id: 'format-1',
      name: 'Combo Reels + Stories (Instagram)',
      description: '1 Reels no feed em collab + sequência de 3 Stories com link e stickers interativos.',
      badge: 'Mais Pedido',
      active: true,
    },
    {
      id: 'format-2',
      name: 'Vídeo Dedicado no TikTok',
      description: '1 Vídeo nativo de alta retenção no TikTok focado em estética, rotina real e engajamento genuíno.',
      badge: 'Alto Alcance',
      active: true,
    },
    {
      id: 'format-3',
      name: 'Embaixadorismo / Contrato Mensal',
      description: 'Parceria contínua de 3 a 6 meses com entregas recorrentes no Instagram & TikTok e direito de uso de imagem.',
      badge: 'Contrato Longo',
      active: true,
    },
    {
      id: 'format-4',
      name: 'Presença VIP em Evento / Workshop',
      description: 'Presença confirmada no evento da marca com cobertura completa em tempo real nos Stories e menção no feed.',
      badge: 'Presencial',
      active: true,
    },
    {
      id: 'format-5',
      name: 'Outro formato personalizado',
      description: 'Formato customizado sob demanda (Live shopping, ensaio fotográfico ou coprodução especial).',
      badge: 'Personalizado',
      active: true,
    },
  ],
};
